# Generated by Django 5.2.1 on 2025-05-20 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_diagnosis_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
    ]
