# Generated by Django 5.2.1 on 2025-05-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
